DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

mayaxing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mysite import views
from DjangoUeditor import urls as DjangoUeditor_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$',views.index, name = 'index'),
    url(r'^news-index/$',views.news_index, name = 'news-index'),
    url(r'^news-index/(?P<pk>\d+)/',views.news_detail, name = 'news-detail'),
    url(r'^blog-index/$',views.blog_index, name = 'blog-index'),
    url(r'^blog-index/(?P<pk>\d+)/',views.blog_detail, name = 'blog-detail'),
    url(r'^share-index/',views.share_index, name = 'share-index'),
    url(r'^register/',views.register, name = 'register'),
    url(r'^login/',views.login, name = 'login'),
    url(r'^logout/',views.logout, name = 'logout'),
    url(r'^tag/(?P<tag>\S+)/',views.tag, name = 'tag'),
    url(r'^userinfo/', views.userinfo, name='userinfo'),
	url(r'^ueditor/',include(DjangoUeditor_urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^ajax_check_username/',views.ajax_check_username, name = 'ajax_check-username'),
    url(r'^ajax_feedback/',views.ajax_feedback, name = 'ajax_feedback')
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib import admin
from django.core.urlresolvers import reverse
from DjangoUeditor.models import UEditorField
import re
from django.utils import timezone
import time
#注册会员---------------------------------------------------------------
class Reg_vip(models.base.Model):
	username = models.CharField(max_length = 20, unique = True)
	password = models.CharField(max_length = 20)
	email = models.EmailField(blank = True)
	reg_time = models.DateTimeField(default = timezone.now)
	user_img = models.FileField(upload_to = 'author_img',blank = True)

	def __str__(self):
		return self.username
		
	class Meta:
		verbose_name_plural = 'A_注册会员'
		ordering = ['-reg_time']

	def get_img_url(self):
		if self.user_img:
			return self.user_img.url
		else:
			return '/upload/author_img/user_normal.jpg'
	def get_author_url(self):
		return reverse('tag',args = (self.username,))

class Reg_vip_admin(admin.ModelAdmin):
	list_display = ('username','password','email','reg_time','user_img')
admin.site.register(Reg_vip,Reg_vip_admin)
#--------------------------------------------------------------------------

#======================================================================================================
#热门网址-------------------------------------------------------------------
class Top_url(models.base.Model):
	name = models.CharField(max_length = 15)
	url = models.URLField()
	logo = models.FileField(upload_to = 'url_logo',blank = True)
	rank = models.IntegerField(blank = True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'B1_热门网址'
		ordering = ['rank']

class Top_url_admin(admin.ModelAdmin):
	list_display = ('name','url','logo','rank')
admin.site.register(Top_url,Top_url_admin)
#--------------------------------------------------------------------------

#分类网址------------------------------------------------------------------
class Sort_tag(models.Model):
	name = models.CharField(max_length = 12)
	rank = models.IntegerField()

	def __str__(self):
		return self.name
		print(self.name)

	class Meta:
		verbose_name_plural = 'B2_分类名称'
		ordering = ['rank']

class Sort_url(models.Model):
	sort = models.ForeignKey(Sort_tag)
	name = models.CharField(max_length = 15)
	url = models.URLField()
	logo = models.FileField(upload_to = 'url_logo',blank = True)
	rank = models.IntegerField()

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'B3_分类网址'
		ordering = ['sort','rank']

class Sort_tag_admin(admin.ModelAdmin):
	list_display = ('name','rank')
admin.site.register(Sort_tag,Sort_tag_admin)

class Sort_url_admin(admin.ModelAdmin):
	list_display = ('sort','name','url','logo','rank')
admin.site.register(Sort_url,Sort_url_admin)
#--------------------------------------------------------------------------------

#==============================================================================================
#新闻标签------------------------------------------------------------------------
class News_tag(models.Model):
	name = models.CharField(max_length = 10)
	tag_img = models.FileField(upload_to = 'tag_img',blank = True)
	rank = models.IntegerField(default = 99)

	def __str__(self):
		return self.name
		ordering = ['rank']

	def get_tag_url(self):
		return reverse ('tag',args = (self.name,))

	class Meta:
		verbose_name_plural = 'C1_新闻标签'

class News_tag_admin(admin.ModelAdmin):
	list_display = ('name','tag_img','rank')
admin.site.register(News_tag,News_tag_admin)
#---------------------------------------------------------------------------------

#新闻来源-------------------------------------------------------------------------
class Origin(models.Model):
	name = models.CharField(max_length = 10)
	url = models.URLField()

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'C2_新闻来源'

class Origin_admin(admin.ModelAdmin):
	list_display = ('name','url')
admin.site.register(Origin,Origin_admin)
#----------------------------------------------------------------------------------

#新闻内容-------------------------------------------------------------------------
class News(models.Model):
	IS_TOP_CHOICES = (
		('Y','yes'),
		('N','no'),
		)
	title = models.CharField(max_length = 50)
	IS_TOP = models.CharField(max_length = 5, choices = IS_TOP_CHOICES, default = 'N' )
	news_tag = models.ManyToManyField(News_tag)
	origin = models.ForeignKey(Origin)
	main_img = models.ImageField(upload_to = 'news_main_img', blank = True)
	published_date = models.DateTimeField(auto_now_add = True)
	# published_date2 = models.CharField(default = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),max_length = 50)
	content = UEditorField('内容', height = 300, width = 1000, default = u'', blank = True, 
		imagePath='news_img/', toolbars='besttome', filePath='news_files/')

	def __str__(self):
		return self.title

	def get_news_abstract(self):
		RE_ABSTRACT = r'<[^>]+>'
		pattern = re.compile(RE_ABSTRACT)
		# print(pattern.sub('',self.content[0:300]))
		return pattern.sub('',self.content[0:500])

	def get_news_url(self):
		return reverse('news-detail',args = (self.pk,))

	class Meta:
		verbose_name_plural = 'C3_新闻内容(编辑)'
		ordering = ['-published_date']

class News_admin(admin.ModelAdmin):
	list_display = ('title','origin','published_date','IS_TOP')
admin.site.register(News,News_admin)
#------------------------------------------------------------------------------------

#新闻评论----------------------------------------------------------------------------
class News_comment(models.Model):
	news_title = models.ForeignKey(News)
	comment = models.ForeignKey(Reg_vip)
	comment_time = models.DateTimeField(auto_now_add = True)
	comment_text = models.TextField(blank = True)

	def __str__(self):
		return self.comment_text
	class Meta:
		verbose_name_plural = ('C4_新闻评论')
		ordering=['-comment_time']

class News_comment_admin(admin.ModelAdmin):
	list_display = ('news_title','comment_time','comment_text')
admin.site.register(News_comment,News_comment_admin)
#--------------------------------------------------------------------------------------

#=======================================================================================================
#博客标签----------------------------------------------------------------------------
class Blog_tag(models.Model):
	name = models.CharField(max_length = 10)
	tag_img = models.FileField(upload_to = 'tag_img',blank = True)
	rank = models.IntegerField(default = 99)

	def __str__(self):
		return self.name
		ordering = ['rank']

	def get_tag_url(self):
		return reverse ('tag',args = [self.name])

	class Meta:
		verbose_name_plural = 'D1_博客标签'

class Blog_tag_admin(admin.ModelAdmin):
	list_display = ('name','tag_img','rank')
admin.site.register(Blog_tag,Blog_tag_admin)
#-------------------------------------------------------------------------------------

#博客内容-----------------------------------------------------------------------------
class Blog(models.Model):
	IS_TOP_CHOICES = (
		('Y','yes'),
		('N','no'),
		)
	IS_TOP = models.CharField(max_length = 5, choices = IS_TOP_CHOICES, default = 'N' )
	blog_author = models.ForeignKey(Reg_vip, on_delete = models.CASCADE)
	title = models.CharField(max_length = 100)
	blog_tag = models.ManyToManyField(Blog_tag, verbose_name = '博客标签',blank = True)
	published_date = models.DateTimeField(default = timezone.now)
	main_img = models.ImageField(upload_to = 'blog_main_img', blank = True)
	content = UEditorField('内容', height = 300, width = 1000, default = u'', blank = True, 
		imagePath='blog_content_img/', toolbars='besttome', filePath='blog_files/')
	blog_read = models.IntegerField(default = 0)
	blog_up = models.IntegerField(default = 0)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name_plural = 'D2_博客内容(编辑)'
		ordering = ['-IS_TOP','-published_date']

	def get_blog_abstract(self):
		RE_ABSTRACT = r'<[^>]+>'
		pattern = re.compile(RE_ABSTRACT)
		# print(pattern.sub('',self.content[0:300]))
		return pattern.sub('',self.content[0:300])

	def get_blog_url(self):
		return reverse('blog-detail',args = (self.pk,))

class Blog_admin(admin.ModelAdmin):
	list_display = ('title','blog_author','IS_TOP','published_date')
admin.site.register(Blog,Blog_admin)
#-------------------------------------------------------------------------------------

#博客评论----------------------------------------------------------------------------
class Blog_comment(models.Model):
	blog_title = models.ForeignKey(Blog, on_delete = models.CASCADE)
	comment = models.ForeignKey(Reg_vip, on_delete = models.CASCADE)
	comment_time = models.DateTimeField(auto_now_add = True)
	comment_text = models.TextField(blank = True)

	def __str__(self):
		return self.comment_text

	class Meta:
		verbose_name_plural = ('D3_博客评论')
		ordering=['-comment_time']
	
class Blog_comment_admin(admin.ModelAdmin):
	list_display = ('blog_title','comment_time','comment_text')
admin.site.register(Blog_comment,Blog_comment_admin)
#--------------------------------------------------------------------------------------

#==========================================================================================
#分享标签------------------------------------------------------------------------
class Share_tag(models.Model):
	tag_name = models.CharField(max_length = 10)

	def __str__(self):
		return self.tag_name

	class Meta:
		verbose_name_plural = ('E1_分享标签')

class Share_tag_admin(admin.ModelAdmin):
	list_display = ('tag_name',)
admin.site.register(Share_tag,Share_tag_admin)
#--------------------------------------------------------------------------------

#分享文件-------------------------------------------------------------------------
class Share_file(models.Model):
	share = models.ForeignKey('Share')
	share_file = models.FileField(upload_to = 'share_file', blank = True)

	class Meta:
		verbose_name_plural = ('E2_分享文件')

	def get_file_name(self):
		return self.share_file.name.split('/')[-1]

class Share_file_admin(admin.ModelAdmin):

templates/blog-detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ blog.title }}{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'css/blog-detail.css' %}">{% endblock %}

{% block content %}
<div class="blogdetail-box">
	<div class="blogdetail-top">
    	<div class="blogdetail-title"><h1>{{ blog.title }}</h1></div>
        <div class="blogdetail-author">
            <img class="blogdetail-img" src="{{ blog.blog_author.get_img_url }}">
            <div class="blogdetail-author-info">
                <span class="author-name">{{ blog.blog_author.username }}</span>
                <span class="published_time">{{ blog.published_date |date:"n月j日 G:i"}}</span>
				<span class="blogdetail-comment"><a href="#blogdetail-comment">评论({{ blog.blog_comment_set.all|length }})</a></span>
            </div>
        </div>
    </div>
    <div class="blogdetail-bottom">
    {{ blog.content | safe}}
    </div>
    <div class="blogdetail-comment" id="blogdetail-comment">
    <form method="post">
        {% for field in cf %}
        {% csrf_token %}
        <div>{{field}}</div>
        {% endfor %}
    
        <div class="log-submit">
            <span class="comment_num">{{ blog.blog_comment_set.all.count }}条评论</span>
            {% if session_username %}
                <span class="username_form"><a href="{% url 'userinfo' %}">{{session_username}}</a></span>
                <input type="submit" class="submit_btn" value="提交">
            {% else %}
                <span class="log_btn"><a href="{% url 'login' %}">登录</a></span>
            {% endif %}
        </div>
    </form>
    <div class="comment-list">
        {% for comment in blog.blog_comment_set.all %}
        <div class="comment-box clearfix">
            <a href="#" class="comment-img"><img src="{{ comment.comment.get_img_url }}" alt=""></a>
            <div class="comment-detail">                
                <div class="comment-name-time"><span class="username">{{ comment.comment }}</span><span class="time">{{ comment.comment_time|date:"n月j日 G:i"}}</span></div>
                <div class="comment-word">{{ comment.comment_text }}</div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}首页{% endblock %}
{% block tag %}<base target="_blank">{% endblock %}
{% block css%}<link rel="stylesheet" href="{% static 'css/index.css' %}">{% endblock %}
{% block js %}<script type="text/javascript" src="../static/javascript/index.js"></script>{% endblock %}
{% block content %}
<div class="body-box fixed-margin-top">
	<div class="body-top clearfix">
    	<div class="body-nav">
        	<div class="nav-hot">
            	<ul class="hot-url-list">
                {% for top_url in top_url %}
                	<li class="hot-url-info"><a href="{{ top_url.url }}" title="{{ top_url.name }}" style="background-image:url({{ top_url.logo.url }})">{{ top_url.name }}</a></li>
                {% endfor %}
                </ul>
            </div>

            <div class="nav-category">
            {% for sort_tag in sort_tag %}
            	<div class="category-box">
                	<span class="category-tag">{{ sort_tag }}</span>
                    <ul class="category-url-list">
                    {% for sort_url in sort_tag.sort_url_set.all|slice:":6" %}
                       	<li class="category-url-info"><a href="{{ sort_url.url }}" style="background-image:">{{ sort_url.name }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
            {% endfor %}
            </div>
        </div>
        <div class="body-side">
        	<div class="ppt" id="ppt">
            	<ul class="ppt-num" id="ppt-num">
                	<li class="num active">•</li>
                    <li class="num">•</li>
                    <li class="num">•</li>
                    <li class="num">•</li>
                </ul>
                <ul class="ppt-img" id="ppt-img">
                    {% for blog_hot in blog_hot %}
                	<li class="img"><a href="{{ blog_hot.get_blog_url }}"><img src="{{ blog_hot.main_img.url }}" alt="图片"></a></li>
                    {% endfor %}
                </ul>
            </div>
            <div>
           	  	<ul class="hot-blog-list">
                    {% for blog_hot in blog_hot %}
                	<li class="hot-blog"><a href="{{ blog_hot.get_blog_url }}" title="{{ blog_hot.title }}">{{ blog_hot.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="tag-list">
                <div class="news-tag-list">
                    <span class="tag-title">资讯标签</span>
                    {% for news_tag in news_tag_list %}
              		<a class="hot-news-tag" href="{{ news_tag.get_tag_url }}">{{ news_tag.name }}</a>
                    {% endfor %}
                </div>
                <div class="blog-tag-list">
                    <span class="tag-title">博客标签</span>
                    {% for blog_tag in blog_tag_list %}
                    <a class="hot-blog-tag" href="{{ blog_tag.get_tag_url }}">{{ blog_tag.name }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
	</div> 
	<div class="body-bottom clearfix">
		<div class="news-blog">
        	<div class="news-list">
            	<div class="colum"><a href="{% url 'news-index' %}">资讯头条</a></div>
                {% for news in news %}
              	<div class="news clearfix">
        			<a href="{{ news.get_news_url }}" class="news-img"><img src="{{ news.main_img.url}}" alt="图片"></a>
           			<div class="news-info">
            			<a href="{{ news.get_news_url }}" title="{{ news.title }}"><h4 class="news-title">{{ news.title }}</h4></a>
                		<div class="news-sub">{#{{ news.get_news_abstract }}#}</div>
                        <div class="news-attach1">
                        	{% for news_tag in news.news_tag.all %}
                            <div class="news-tag"><a href="{{ news_tag.get_tag_url }}">{{ news_tag.name }}</a></div>
                            {% endfor %}
                        </div>
                        <div class="news-attach2">
							<div class="published-time">{{ news.published_date |date:"n月j日  G:i"}}</div>
                            <div class="comment-share"><a href="{{ news.get_news_url }}#newsdetail-comment">评论（{{ news.news_comment_set.all.count }}）</a></div>
                        </div>
             	 	</div>
            	</div>
                {% endfor %}
            </div>
    
     		<div class="blog-list">
				<div class="colum"><a href="{% url 'blog-index' %}">博客排行</a></div>
                {% for blog in blog %}
                <div class="blog-info">
                    {% if blog.main_img %}
                    <div class="blog-info-img"><img src="{{ blog.main_img.url }}" alt=""></div>
                    {% endif %}
                    <div class="blog-title-abstract">
                        <div class="blog-title-time">
                        <a href="{{ blog.get_blog_url }}" class="blog-title">{{ blog.title }}</a>
                        <span class="blog-time">{{ blog.published_date|date:"n月j日 G:i" }}</span>
                    </div>
                    <div class="blog-abstract">{{ blog.get_blog_abstract }}</div>
                </div>  
                </div>
                {% endfor %}
            </div>
        </div>
      	<div class="share-list">
        	<div class="colum"><a href="{% url 'share-index' %}">热门分享</a></div>
            {% for share in share %}
            <div class="share-info">
                <div class="share-author-title">
                    <div class="author-img"><img src="{{share.author.user_img.url }}"></div>
                    <div class="author-name">{{ share.author.username }}</div>
                    <div class="share-title"><a href="{% url 'share-index' %}#{{share.share_title}}">{{ share.share_title }}</a></div>
                </div>
                <div class="share-desc">{{ share.share_desc }}</div>
                {% for share_file in share.share_file_set.all %}
                <div class="share-file"><a href="{% url 'share-index' %}#{{share.share_title}}">{{ share_file.get_file_name }}</a></div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
	</div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}登录{% endblock %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">{% endblock %}

{% block content %}
<div class="register">
    <div class="register-name">登  录</div>
    <form method="post">
    {% csrf_token %}
    	<p class="label">{{ uf.username.label }}</p>
    	{{ uf.username }}
    	{{ uf.username.errors }}
    	<p class="label">{{ uf.password.label }}</p>
    	{{ uf.password }}
    	{{ uf.password.errors }}
    {% if is_login %}
    <p class="is_login">用户名或密码错误</p>
    {% endif %}
    <input type="submit" value="登录" class="submit">
	</form> 
</div>
{% endblock %}

templates/news-detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ news.title }}{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'css/news-detail.css' %}">{% endblock %}
{% block content %}

<div class="newsdetail-box clearfix">
	<div class="newsdetail-news ">
    	<div class="newsdetail-content">
        	<div class="newsdetail-top">
            	<h2 class="newsdetail-title">{{ news.title }}</h2>
                <div class="newsdetail-attach">
                	<div class="newsdetail-from"><a href="{{ news.origin.url }}">{{ news.origin }}</a></div>
                    {% for news_tag in news.news_tag.all %} 
                    <div class="newsdetail-tag"><a href="{{ news_tag.get_tag_url }}">{{ news_tag }}</a></div>
                    {% endfor %}
                    <div class="newsdetail-time">{{ news.published_date|date:"n月j日 G:i" }}</div>
                    <div class="newsdetail-comment-top"><a href="#newsdetail-comment">评论({{news.news_comment_set.all.count}})</a></div>
                </div>
            </div>
            <div class="newsdetail-body">
            {{ news.content | safe }}
            </div>
        </div>
        <div class="newsdetail-comment" id="newsdetail-comment">
            <form method="post">
                {% for field in cf %}
                {% csrf_token %}
                <div>{{field}}</div>
                {% endfor %}
            
                <div class="log-submit">
                    <span class="comment_num">{{ news.news_comment_set.all.count }}条评论</span>
                    {% if session_username %}
                        <span class="username_form"><a href="{% url 'userinfo' %}">{{session_username}}</a></span>
                        <input type="submit" class="submit_btn" value="提交">
                    {% else %}
                        <span class="log_btn"><a href="{% url 'login' %}">登录</a></span>
                    {% endif %}
                </div>
            </form>
            <div class="comment-list">
            	{% for comment in news.news_comment_set.all %}
            	<div class="comment-box clearfix">
                	<a href="#" class="comment-img"><img src="{{comment.comment.get_img_url}}" alt=""></a>
					<div class="comment-detail">                
                        <div class="comment-name-time"><span class="username">{{ comment.comment }}</span><span class="time">{{ comment.comment_time|date:"n月j日 G:i" }}</span></div>
                        <div class="comment-word">{{ comment.comment_text }}</div>

                	</div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="newsdetail-relative">
    	<div class="relative-news">相关新闻</div>
        <div class="relative-list">
            {% for news_tag in news_tag_list %}
        	<ul>
                {% for each_news in news_tag.news_set.all %}
                {% if each_news.pk != news.pk %}
            	<li><a href="{{each_news.get_news_url }}">{{ each_news.title }}</a></li>
                {% endif %}
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/share-index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}分享{% endblock %}
{% block css%}<link rel="stylesheet" href="{% static 'css/share-index.css' %}">{% endblock %}
{% block content %}
<div class="share-box">
	<div class="share-name">分享</div>
    <div class="share-list">
    	{% for share in share_list %}
    	<div class="share-info clearfix">
        	<div class="author-info">
            	<div class="author-img"><a href="{{ share.author.get_author_url }}"><img src="{{ share.author.user_img.url }}"></a></div>
                <div class="author-name">{{ share.author.username }}</div>
                <div class="share-num">{{ share.author.share_set.all.count }}次分享</div>
                <!-- <div class="file-num">{#{}#}个文件</div> -->
            </div>
            <div class="file-info">
        		<div class="share-title-tag">
                    <h4 class="share-title" id="{{ share.share_title }}">{{ share.share_title }}</h4>
                    {% for share_tag in share.share_tag.all %}
                    <span class="share-tag">{{ share_tag.tag_name }}</span>
                    {% endfor %}
                </div>  
                <div class="share-desc">{{ share.share_desc }}</div>
                {% for share_file in share.share_file_set.all %}
                <div class="share-file"><span>附件{{forloop.counter}}:</span><a class="share_url "href="{{ share_file.share_file.url }}">{{ share_file.get_file_name }}</a></div>
                {% endfor %}
        	</div>
    	</div>
        {% endfor %}
	</div>
</div>
{% endblock %}

templates/success-reg.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}注册成功{% endblock %}
{% block css%}<link rel="stylesheet" href="{% static 'css/success_reg.css' %}">{% endblock %}
{% block content %}
<div class="success">
<span>恭喜你</span>，<span class="username-success">{{username}}</span>，<span>注册成功！</span>
<a href="{% url 'index' %}" class="to-index">点击返回首页</a> 
</div>
{% endblock %}

templates/tag.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{news_tag.name}}{{author_tag.username}}{{blog_tag.name}}__标签{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'css/tag.css' %}">{% endblock %}
{% block content %}

<div class="tagdetail-box">
	<div class="tag-name">{{news_tag.name}}{{author_tag.username}}{{blog_tag.name}}<span>所有文章</span></div>
    <div class="tagdetail-list">
        {% if news_tag %}
        
        {% for each_news in news_tag.news_set.all %}
        <div class="tag-info">
        	<div class="tag-info-img"><img src="{{each_news.main_img.url}}" alt=""></div>
            <div class="tag-title-abstract">
            	<div class="tag-title-time">
                <a href="{{ each_news.get_news_url }}" class="tag-title">{{each_news.title}}</a>
                <span class="tag-time">{{ each_news.published_date|date:"n月j日 G:i"}}</span>
                </div>
                <div class="tag-abstract">{{each_news.get_news_abstract }}</div>
            </div>  
        </div>
        {% endfor %}
        
        {% elif blog_tag %}
        
        {% for each_blog in blog_tag.blog_set.all %}
		<div class="tag-info">
        	{% if each_blog.main_img %}
        	<div class="tag-info-img"><img src="{{each_blog.main_img.url}}" alt=""></div>
            {% endif %}
            <div class="tag-title-abstract">
            	<div class="tag-title-time">
                <a href="{{ each_blog.get_blog_url }}" class="tag-title">{{each_blog.title}}</a>
                <span class="tag-time">{{ each_blog.published_date|date:"n月j日 G:i"}}</span>
                </div>
                <div class="tag-abstract">{{each_blog.get_blog_abstract }}</div>
            </div>  
        </div>
        {% endfor %}
        
        {% else %}
        
        {% for each_author in author_tag.blog_set.all %}
		<div class="tag-info">
        	{% if each_author.main_img %}
        	<div class="tag-info-img"><img src="{{each_author.main_img.url}}" alt=""></div>
            {% endif %}
            <div class="tag-title-abstract">
            	<div class="tag-title-time">
                <a href="{{ each_author.get_blog_url }}" class="tag-title">{{each_author.title}}</a>
                <span class="tag-time">{{ each_author.published_date|date:"n月j日 G:i"}}</span>
                </div>
                <div class="tag-abstract">{{each_author.get_blog_abstract }}</div>
            </div>  
        </div>
        {% endfor %}

        {% endif %}
    </div>

</div>
{% endblock %}

templates/userinfo.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="../static/css/userinfo.css">
<title>个人中心--RunCode</title>
</head>

<body>
<div class="userbox">个人中心正在建设中...<br><br><a href="{% url 'index' %}">返回首页</a></div>
</body>
</html>